// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "]QO]T1{RHeD0P~8POYve":
            case "PlayAlienIdle":return img`
............................
.............ccc............
............cbbbc...........
...........c7bbbc...........
...........cb75b5...........
............cbbbc...........
..........cc6cccf...........
.........cbbc6666...........
.........cbbc66666..........
........cbbc666666..........
........cbbc66cc6c6.........
.......6cbc.ccbbc66.........
.......66c.eeebcbe66........
.......666.eddeeede6........
........66eddddddde6........
........66edddeedde66.......
.......666cdddeddde6c.......
.......c66cddeedddec........
........ceddeeedde..........
.........eddeeddde..........
.........edddeddde..........
.........edddedde...........
..........cddeddc...........
..........eeeceee...........
.........eeeeceee...........
........eeeecceeee..........
........eeeeccceeee.........
........ccccc.ccccc.........
`;
            case "image2":
            case "PlayAlienJump":return img`
............................
............................
..............ccc...........
.............cbbbc..........
............c7bbbc..........
............cb75b5..........
..........cc6cbbbcc.........
.........cbbc6ccc6bc........
.........cbbc66666bc........
........cbbc666666bbc.......
.......6bbbc66cc6cbb6.......
.......66bc.ccbbc.66cc......
.......666.eeebcbe6c66......
........66.eddeeede66.......
........66eddddddde.........
.......666cdddeeddde........
.......c66cdddeeedde........
........cedddeeeddde........
.........edddeeddde.........
..........eddeeede..........
..........eddeeeee..........
..........eddeceeee.........
..........cddc.ceeee........
..........eeec..cccc........
..........eee...............
.........eeec...............
.........eeec...............
.........ccc................
`;
            case "image3":
            case "Key":return img`
. 5 5 . . . 5 5 5 5 . . . 5 5 . 
5 5 5 5 5 b 5 b b 5 b 5 5 5 5 5 
b 5 5 5 5 b 5 c c 5 b 5 5 5 5 b 
5 5 5 5 5 b 5 c c 5 b 5 5 5 5 5 
5 5 5 5 5 b 5 c c 5 b 5 5 5 5 5 
5 5 5 5 5 b 5 c c 5 b 5 5 5 5 5 
5 5 5 5 5 b c b d c b 5 5 5 5 5 
5 5 5 5 5 b c d b c b 5 5 5 5 5 
5 5 5 5 5 b 5 c c 5 b 5 5 5 5 5 
5 5 3 5 5 5 b 5 5 b 5 5 5 3 5 5 
5 5 1 3 5 5 5 b b 5 5 5 3 1 5 5 
5 5 5 1 3 5 5 5 5 5 5 3 1 5 5 5 
b 5 5 5 1 3 5 5 5 5 3 1 5 5 5 b 
5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 
b 5 5 5 5 5 5 5 5 5 5 5 5 5 5 b 
. b b b b b b b b b b b b b b . 
`;
            case "image1":
            case "PlayAlienFall":return img`
............................
..............ccc...........
.............cbbbc..........
............c7bbbc..........
............cb75b5..........
..........ccfcbbbcc.........
.........cbbc6cccfbc........
........cbbbc66666bc........
.......6bbbc666666bbc.......
.......66bc.666666bb6.......
.......666..66cc6c666.......
........66..ccbbc.6666......
........66.eeebcbe.666......
.......666ceddeeedec66......
.......c66cddddddde.6c......
........c.edddeedddec.......
.........eddddedddde........
.........edddeeedddde.......
.........eddee..eddde.......
.........eddde.eddde........
.........edddeeedde.........
..........cddeeddc..........
..........eeeceeee..........
.........eeeeceeee..........
.........eeec.ceeee.........
........eeeec..ceeee........
........cccc....cccc........
............................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
